---
- name: creating icinga2 dynamic host object(s)
  uri:
    user: "{{ icinga2_api_user }}"
    password: "{{ icinga2_api_pass }}"
    url: "https://{{ icinga2_hostname }}:5665/v1/objects/hosts/{{ icinga2_dynamic_host.name }}"
    method: "{{ icinga2_api_method | default('PUT') }}"
    HEADER_Accept: "application/json"
    body: "{{ icinga2_dynamic_host.info }}"
    body_format: json
    validate_certs: no
    return_content: yes
    status_code: ["200", "503"]
  register: _icinga2_dynamic_hosts
  delegate_to: "{{ icinga2_hostname }}"
  changed_when: "_icinga2_dynamic_hosts.status == 200"
  tags: icinga2_api_dynamic_hosts
