---
- hosts: icinga2a:icinga2b
  become: yes
  tasks:
    - name: setting static, transient and pretty hostnames
      hostname:
        name: "{{ icinga2_hostname }}"
      tags: hostname

- hosts: icinga2a:icinga2b
  become: yes
  tasks:
    - name: updating /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: "{{ ansible_eth1.ipv4.address }}"
        line: "{{ ansible_eth1.ipv4.address }} {{ ansible_hostname }}"
      tags: hostname

- hosts: all:!localhost
  become: yes
  roles:
    - role: ntp
      tags: ntp

    - role: timezone
      tags: timezone

    - role: packages
      tags: packages

    - role: icinga2-no-ui
      tags: icinga2-no-ui

    - role: icinga2-api/hostgroups
      tags: icinga2-api

    - role: icinga2-api/static_hosts
      tags: icinga2-api

    - role: icinga2-api/servicegroups
      tags: icinga2-api

    - role: icinga2-api/users
      tags: icinga2-api

    - role: icinga2-api/services
      tags: icinga2-api
