---
staff:
  djohnson:
    name: Drew Johnson
    e-mail: drew.johnson@gmail.com
    password: Diu3aagh
  dvaida:
    name: Dan Vaida
    e-mail: vaida.dan@gmail.com
    password: deNgeG5o
  kschmidt:
    name: Karl Schmidt
    e-mail: karl.schmidt@gmail.com
    password: Too7vooh
