---
- name: creating icinga2 static host object(s)
  uri:
    user: "{{ icinga2_api_user }}"
    password: "{{ icinga2_api_pass }}"
    url: "https://{{ icinga2_hostname }}:5665/v1/objects/hosts/{{ item.name }}"
    method: "{{ icinga2_api_method | default('PUT') }}"
    HEADER_Accept: "application/json"
    body: "{{ item.info }}"
    body_format: json
    validate_certs: no
    return_content: yes
    status_code: ["200", "503"]
  register: _icinga2_static_hosts
  with_items: icinga2_static_hosts
  changed_when: "_icinga2_static_hosts.status == 200"
  tags: icinga2_api_static_hosts
