---
- name: cross-OS play
  hosts: all
  sudo: yes
  tasks:

    - apt: name=vim state=latest update_cache=yes
      when: ansible_distribution == "Debian"

    - name: installing Vim on Red-Hat based OS
      yum:
        name: vim
        state: latest
      when: ansible_distribution in [ 'CentOS', 'Fedora' ] 
