---
- name: installing all required packages
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - "{{ inst_pkgs.common }}"
    - "{{ inst_pkgs.redhat }}"

- name: installing dependencies | "{{ packages }}"
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  when: packages is defined

- name: installing python packages through pip
  pip:
    name: "{{ item }}"
  when: '"python-pip" in inst_pkgs.common'
  with_items: "{{ python_pkgs }}"

- name: uninstalling unwanted packages
  yum:
    name: "{{ item }}"
    state: absent
  with_items: "{{ remv_pkgs.redhat }}"
