---

- hosts: all
  sudo: yes

  roles:
    - { role: lesmyrmidons.mongodb }
    - { role: f500.elasticsearch }

  vars_files:
    - defaults/main.yml
    - defaults/{{ ansible_distribution }}.yml

  tasks:
    - include: tasks/main.yml

  handlers:
    - include: handlers/main.yml
