---
icinga2_key:      'http://packages.icinga.org/icinga.key'

icinga2_url_yum:  'http://packages.icinga.org/epel/ICINGA-release.repo'
icinga2_repo_yum: '/etc/yum.repos.d/ICINGA-release.repo'

icinga2_yum:
  - 'icinga2'
  - 'nagios-plugins-all'

icinga2_main_conf: '/etc/icinga2/icinga2.conf'
icinga2_conf_d:    '/etc/icinga2/conf.d'

icinga2_conf_global: |
  include "constants.conf"
  include "zones.conf"
  include <itl>
  include <plugins>
  include "features-enabled/*.conf"
  include_recursive "conf.d"
